"""
MediSense AI v2 — PDF Report Generator
Produces a downloadable AI health assessment report using reportlab.
Install: pip install reportlab
"""
import io
from datetime import datetime

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, KeepTogether
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


DISCLAIMER = (
    "IMPORTANT DISCLAIMER: This report is generated by an AI system for "
    "educational and informational purposes ONLY. It does NOT constitute a "
    "medical diagnosis and must NOT be used as a substitute for professional "
    "medical advice, diagnosis, or treatment. Always consult a qualified and "
    "licensed healthcare professional for any health concerns or before making "
    "any medical decisions."
)

GREEN  = colors.HexColor("#2d6a4f")
LGREEN = colors.HexColor("#e8f4ee")
RED    = colors.HexColor("#c84b31")
WARN   = colors.HexColor("#d4862a")
LWARN  = colors.HexColor("#fef6ea")
GREY   = colors.HexColor("#6b6460")
BGREY  = colors.HexColor("#f5f2ee")


def generate_report(
    symptoms: list[str],
    predictions: list[dict],
    patient_name: str = "Patient",
    report_id: str = None,
) -> bytes:
    """
    Generate a PDF report and return it as bytes.

    Args:
        symptoms    : List of matched symptom strings
        predictions : Top-3 prediction dicts from PredictionService.predict()
        patient_name: Optional patient name
        report_id   : Optional unique report ID

    Returns:
        PDF as bytes (ready for Flask send_file)
    """
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError(
            "reportlab is required for PDF generation. "
            "Install with: pip install reportlab"
        )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=20*mm, leftMargin=20*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )

    styles = getSampleStyleSheet()
    story  = []

    # ── Header ────────────────────────────────────────────────────────────────
    header_style = ParagraphStyle(
        "header", fontSize=22, textColor=GREEN,
        fontName="Helvetica-Bold", spaceAfter=2*mm,
    )
    sub_style = ParagraphStyle(
        "sub", fontSize=10, textColor=GREY,
        fontName="Helvetica", spaceAfter=4*mm,
    )
    story.append(Paragraph("MediSense AI", header_style))
    story.append(Paragraph("AI-Powered Health Assessment Report", sub_style))
    story.append(HRFlowable(width="100%", thickness=1, color=GREEN, spaceAfter=6*mm))

    # ── Meta info table ───────────────────────────────────────────────────────
    ts = datetime.now().strftime("%d %B %Y, %H:%M")
    rid = report_id or f"MS-{datetime.now().strftime('%Y%m%d%H%M%S')}"

    meta_data = [
        ["Patient Name", patient_name, "Report ID", rid],
        ["Generated At", ts,           "Model",     "Random Forest v2.0"],
    ]
    meta_table = Table(meta_data, colWidths=[35*mm, 65*mm, 30*mm, 40*mm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",  (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE",  (0,0), (-1,-1), 9),
        ("TEXTCOLOR", (0,0), (0,-1), GREY),
        ("TEXTCOLOR", (2,0), (2,-1), GREY),
        ("FONTNAME",  (1,0), (1,-1), "Helvetica-Bold"),
        ("FONTNAME",  (3,0), (3,-1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
        ("TOPPADDING",    (0,0), (-1,-1), 3),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8*mm))

    # ── Symptoms section ──────────────────────────────────────────────────────
    sec_style = ParagraphStyle(
        "sec", fontSize=13, textColor=GREEN,
        fontName="Helvetica-Bold", spaceBefore=4*mm, spaceAfter=3*mm,
    )
    body_style = ParagraphStyle(
        "body", fontSize=10, textColor=colors.black,
        fontName="Helvetica", spaceAfter=2*mm, leading=15,
    )
    story.append(Paragraph("Reported Symptoms", sec_style))

    sym_display = [s.replace("_", " ").title() for s in symptoms]
    sym_rows = [sym_display[i:i+3] for i in range(0, len(sym_display), 3)]
    sym_padded = [row + [""] * (3 - len(row)) for row in sym_rows]

    if sym_padded:
        sym_table = Table(sym_padded, colWidths=[57*mm, 57*mm, 57*mm])
        sym_table.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,-1), LGREEN),
            ("TEXTCOLOR",    (0,0), (-1,-1), GREEN),
            ("FONTNAME",     (0,0), (-1,-1), "Helvetica-Bold"),
            ("FONTSIZE",     (0,0), (-1,-1), 9),
            ("ALIGN",        (0,0), (-1,-1), "CENTER"),
            ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
            ("ROWBACKGROUND",(0,0), (-1,-1), [LGREEN, colors.white]),
            ("BOTTOMPADDING",(0,0), (-1,-1), 5),
            ("TOPPADDING",   (0,0), (-1,-1), 5),
            ("GRID",         (0,0), (-1,-1), 0.5, colors.white),
            ("ROUNDEDCORNERS", (0,0), (-1,-1), [3]),
        ]))
        story.append(sym_table)
    else:
        story.append(Paragraph("No symptoms recorded.", body_style))

    story.append(Spacer(1, 6*mm))

    # ── Predictions section ───────────────────────────────────────────────────
    story.append(Paragraph("AI Disease Assessment (Top 3)", sec_style))
    story.append(Paragraph(
        "The following conditions were identified based on the reported symptoms "
        "and their severity scores. Probabilities reflect model confidence.",
        ParagraphStyle("note", fontSize=9, textColor=GREY, fontName="Helvetica", spaceAfter=4*mm),
    ))

    for i, pred in enumerate(predictions):
        rank = ["Primary Assessment", "Secondary Assessment", "Tertiary Assessment"][i]
        bg   = LGREEN if i == 0 else BGREY
        border_color = GREEN if i == 0 else colors.HexColor("#e8e3dc")

        # Probability bar approximation using table columns
        bar_filled = max(1, int(pred["probability"] / 5))  # scale to ~20 cols
        bar_empty  = 20 - bar_filled

        block = [
            [
                Paragraph(f"<b>{rank}</b>", ParagraphStyle("r", fontSize=8, textColor=GREY, fontName="Helvetica")),
                Paragraph(f"<b>{pred['probability']}%</b>",
                          ParagraphStyle("p", fontSize=11, textColor=GREEN, fontName="Helvetica-Bold",
                                         alignment=TA_RIGHT)),
            ],
            [
                Paragraph(pred["disease"],
                          ParagraphStyle("d", fontSize=14, fontName="Helvetica-Bold",
                                         textColor=colors.black)),
                Paragraph(f"Specialist: {pred['specialization']}",
                          ParagraphStyle("s", fontSize=9, textColor=GREY, fontName="Helvetica",
                                         alignment=TA_RIGHT)),
            ],
        ]
        block_table = Table(block, colWidths=[120*mm, 51*mm])
        block_table.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), bg),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4),
            ("TOPPADDING",    (0,0), (-1,-1), 4),
            ("LEFTPADDING",   (0,0), (0,-1), 4),
            ("RIGHTPADDING",  (-1,0),(-1,-1), 4),
            ("BOX",           (0,0), (-1,-1), 1, border_color),
            ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(KeepTogether([block_table, Spacer(1, 1*mm)]))

        # Description
        if pred.get("description"):
            story.append(Paragraph(pred["description"][:300] + "…" if len(pred.get("description","")) > 300 else pred.get("description",""),
                                   ParagraphStyle("desc", fontSize=9, textColor=colors.black,
                                                  fontName="Helvetica", leftIndent=4*mm, spaceAfter=2*mm, leading=13)))

        # Precautions
        if pred.get("precautions"):
            story.append(Paragraph("<b>Recommended Precautions:</b>",
                                   ParagraphStyle("ph", fontSize=9, textColor=GREEN,
                                                  fontName="Helvetica-Bold", leftIndent=4*mm)))
            for p in pred["precautions"]:
                story.append(Paragraph(f"• {p}",
                                       ParagraphStyle("pi", fontSize=9, textColor=colors.black,
                                                      fontName="Helvetica", leftIndent=8*mm, leading=13)))
        story.append(Spacer(1, 5*mm))

    # ── Disclaimer ────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=WARN, spaceBefore=4*mm, spaceAfter=4*mm))
    disc_style = ParagraphStyle(
        "disc", fontSize=8, textColor=WARN, fontName="Helvetica",
        leading=12, borderPad=4, backColor=LWARN,
        borderColor=WARN, borderWidth=0.5, borderRadius=3,
    )
    story.append(Paragraph(DISCLAIMER, disc_style))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 6*mm))
    story.append(Paragraph(
        f"Generated by MediSense AI v2.0 · {ts} · For educational use only.",
        ParagraphStyle("footer", fontSize=7, textColor=GREY,
                       fontName="Helvetica", alignment=TA_CENTER),
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()
